language_names = {
  "af": ["Afrikaans","Afrikaans"],
  "ak": ["Akan","Akan"],
  "sq": ["Albanian","Shqip"],
  "am": ["Amharic","አማርኛ"],
  "ar": ["Arabic","العربية"],
  "hy": ["Armenian","Հայերեն"],
  "rup": ["Aromanian","Armãneashce"],
  "as": ["Assamese","অসমীয়া"],
  "az": ["Azerbaijani","Azərbaycan dili"],
  "az-tr": ["Azerbaijani (Turkey)","Azərbaycan Türkcəsi"],
  "ba": ["Bashkir","башҡорт теле"],
  "eu": ["Basque","Euskara"],
  "bel": ["Belarusian","Беларуская мова"],
  "bn": ["Bengali","বাংলা"],
  "bs": ["Bosnian","Bosanski"],
  "bg": ["Bulgarian","Български"],
  "mya": ["Burmese","ဗမာစာ"],
  "ca": ["Catalan","Català"],
  "bal": ["Catalan (Balear)","Català (Balear)"],
  "zh": ["Chinese","中文"],
  "zh-cn": ["Chinese (China)","中文"],
  "zh-hk": ["Chinese (Hong Kong)","香港中文版"],
  "zh-tw": ["Chinese (Taiwan)","中文"],
  "co": ["Corsican","corsu"],
  "hr": ["Croatian","Hrvatski"],
  "cs": ["Czech","čeština‎"],
  "da": ["Danish","Dansk"],
  "nl": ["Dutch","Nederlands"],
  "nl-be": ["Dutch (Belgium)","Nederlands (België)"],
  "en": ["English","English"],
  "en-au": ["English (Australia)","English (Australia)"],
  "en-ca": ["English (Canada)","English (Canada)"],
  "en-gb": ["English (UK)","English (UK)"],
  "eo": ["Esperanto","Esperanto"],
  "et": ["Estonian","Eesti"],
  "fo": ["Faroese","føroyskt"],
  "fi": ["Finnish","Suomi"],
  "fr-be": ["French (Belgium)","Français de Belgique"],
  "fr": ["French (France)","Français"],
  "fy": ["Frisian","Frysk"],
  "fuc": ["Fulah","Pulaar"],
  "gl": ["Galician","Galego"],
  "ka": ["Georgian","ქართული"],
  "de": ["German","Deutsch"],
  "el": ["Greek","Ελληνικά"],
  "gn": ["Guaraní","Avañe'ẽ"],
  "haw": ["Hawaiian","Ōlelo Hawaiʻi"],
  "haz": ["Hazaragi","هزاره گی"],
  "he": ["Hebrew","עברית"],
  "hi": ["Hindi","हिन्दी"],
  "hu": ["Hungarian","Magyar"],
  "is": ["Icelandic","Íslenska"],
  "id": ["Indonesian","Bahasa Indonesia"],
  "ga": ["Irish","Gaelige"],
  "it": ["Italian","Italiano"],
  "ja": ["Japanese","日本語"],
  "jv": ["Javanese","Basa Jawa"],
  "kn": ["Kannada","ಕನ್ನಡ"],
  "kk": ["Kazakh","Қазақ тілі"],
  "km": ["Khmer","ភាសាខ្មែរ"],
  "rw": ["Kinyarwanda","Kinyarwanda"],
  "ky": ["Kirghiz","кыргыз тили"],
  "ko": ["Korean","한국어"],
  "ckb": ["Kurdish (Sorani)","كوردی‎"],
  "lo": ["Lao","ພາສາລາວ"],
  "lv": ["Latvian","latviešu valoda"],
  "li": ["Limburgish","Limburgs"],
  "lt": ["Lithuanian","Lietuvių kalba"],
  "lb": ["Luxembourgish","Lëtzebuergesch"],
  "mk": ["Macedonian","македонски јазик"],
  "mg": ["Malagasy","Malagasy"],
  "ms": ["Malay","Bahasa Melayu"],
  "ml": ["Malayalam","മലയാളം"],
  "mr": ["Marathi","मराठी"],
  "xmf": ["Mingrelian","მარგალური ნინა"],
  "mn": ["Mongolian","Монгол"],
  "me": ["Montenegrin","Crnogorski jezik"],
  "ne": ["Nepali","नेपाली"],
  "nb": ["Norwegian (Bokmål)","Norsk bokmål"],
  "nn": ["Norwegian (Nynorsk)","Norsk nynorsk"],
  "os": ["Ossetic","Ирон"],
  "ps": ["Pashto","پښتو"],
  "fa": ["Persian","فارسی"],
  "fa-af": ["Persian (Afghanistan)","فارسی (افغانستان"],
  "pl": ["Polish","Polski"],
  "pt-br": ["Portuguese (Brazil)","Português do Brasil"],
  "pt": ["Portuguese (Portugal)","Português"],
  "pa": ["Punjabi","ਪੰਜਾਬੀ"],
  "rhg": ["Rohingya","Rohingya"],
  "ro": ["Romanian","Română"],
  "ru": ["Russian","Русский"],
  "ru-ua": ["Russian (Ukraine)","украї́нська мо́ва"],
  "rue": ["Rusyn","Русиньскый"],
  "sah": ["Sakha","Sakha"],
  "sa-in": ["Sanskrit","भारतम्"],
  "srd": ["Sardinian","sardu"],
  "gd": ["Scottish Gaelic","Gàidhlig"],
  "sr": ["Serbian","Српски језик"],
  "sd": ["Sindhi","سندھ"],
  "si": ["Sinhala","සිංහල"],
  "sk": ["Slovak","Slovenčina"],
  "sl": ["Slovenian","slovenščina"],
  "so": ["Somali","Afsoomaali"],
  "azb": ["South Azerbaijani","گؤنئی آذربایجان"],
  "es-ar": ["Spanish (Argentina)","Español de Argentina"],
  "es-cl": ["Spanish (Chile)","Español de Chile"],
  "es-co": ["Spanish (Colombia)","Español de Colombia"],
  "es-mx": ["Spanish (Mexico)","Español de México"],
  "es-pe": ["Spanish (Peru)","Español de Perú"],
  "es-pr": ["Spanish (Puerto Rico)","Español de Puerto Rico"],
  "es": ["Spanish (Spain)","Español"],
  "es-ve": ["Spanish (Venezuela)","Español de Venezuela"],
  "su": ["Sundanese","Basa Sunda"],
  "sw": ["Swahili","Kiswahili"],
  "sv": ["Swedish","Svenska"],
  "gsw": ["Swiss German","Schwyzerdütsch"],
  "tl": ["Tagalog","Tagalog"],
  "tg": ["Tajik","тоҷикӣ"],
  "ta": ["Tamil","தமிழ்"],
  "ta-lk": ["Tamil (Sri Lanka)","தமிழ்"],
  "tt": ["Tatar","Татар теле"],
  "te": ["Telugu","తెలుగు"],
  "th": ["Thai","ไทย"],
  "bo": ["Tibetan","བོད་སྐད"],
  "tir": ["Tigrinya","ትግርኛ"],
  "tr": ["Turkish","Türkçe"],
  "tuk": ["Turkmen","Türkmençe"],
  "ug": ["Uighur","Uyƣurqə"],
  "uk": ["Ukrainian","Українська"],
  "ur": ["Urdu","اردو"],
  "uz": ["Uzbek","O‘zbekcha"],
  "vi": ["Vietnamese","Tiếng Việt"],
  "wa": ["Walloon","Walon"],
  "cy": ["Welsh","Cymraeg"]
};
